### ISSUE TITLE
Memory-Test does not evaluate a single model 

### ISSUE THREAD

**Issue by xuevin** [CyberZHG/keras-transformer-xl#6]
**Describe the Bug**

I believe that test is intended to evaluate the Memory function for 10 batches of sentences (or the same sentence for 10 epochs). 

The current implementation initializes the Model 10x instead of initializing one model and evaluating 10 batches. 

**Version Info**

* [x] I'm using the latest version

**Minimal Codes To Reproduce**
NA

I think the recommended change is to shift the model instantiation outside of the for loop. 

```python
        for _ in range(10):
            input_data = keras.layers.Input(shape=(3, 3))
            input_length = keras.layers.Input(shape=(1,))
            output = Memory(3, 5, 3, 3)([input_data, input_length])
            model = keras.models.Model(
                inputs=[input_data, input_length],
                outputs=output,
            )
            ....
```

```python
        input_data = keras.layers.Input(shape=(3, 3))
        input_length = keras.layers.Input(shape=(1,))
        output = Memory(3, 5, 3, 3)([input_data, input_length])
        model = keras.models.Model(
            inputs=[input_data, input_length],
            outputs=output,
        )
        for _ in range(10):
            ...
```

**Comment by CyberZHG** [comment]
No. This is intend to make sure the order of calculation is correct.

See [Use more memory to avoid ordering issue](https://github.com/CyberZHG/keras-transformer-xl/commit/50231560a5c0404ad7e13f328527d18809ab9146)

**Comment by xuevin** [comment]
I see. This deals with the case that multiple models are loaded in the same session.

https://github.com/CyberZHG/keras-transformer-xl/blob/50231560a5c0404ad7e13f328527d18809ab9146/keras_transformer_xl/sequence.py#L39

I thought that this test was used to evaluate the memory reset at the end of a batch. 
Thank you for the clarification!

**Comment by xuevin** [comment]
I am not following why the nested function needs to be executed 10x. Given that you are calling Memory inside the for loop, it reinitializes the state, such that the output will always be the same.

**Comment by CyberZHG** [comment]
Because before that commit, the memory block produces wrong output with a random probability. I have to make sure it always produces the expected output.

**Comment by xuevin** [comment]
Thanks for clarifying. I appreciate your work!
