### ISSUE TITLE
I find the structure has a little difference to official model.

### ISSUE THREAD

**Issue by wiseh2o** [CyberZHG/keras-transformer-xl#9]
I use the latest code to build a transformer-xl model and load the checkpoints trained from official code. It predicts right, but gets a much bigger loss when continue training.

Thus, I make a compare with official code. I find that there are two difference in structure:
1.  There is a wrong order between ```dropout layer```  and ```add layer```. ```dropout``` is first in official code both in ```attention layer``` and ``` feed forward layer```.
2. There is a ```dropout layer``` missing before ```softmax```

Then I try modify the code and it seams run correctly.

Could you please make a double check?

**Comment by CyberZHG** [comment]
Thanks. I've updated the codes.
